# Generated by Django 4.0 on 2022-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='default_image.jpg', null=True, upload_to=''),
        ),
    ]
