# Generated by Django 4.0.4 on 2022-07-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
