# Generated by Django 4.0.4 on 2022-08-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='thumb',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
