# Generated by Django 4.0.4 on 2022-08-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_avatar_profile_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to='default.png'),
        ),
    ]
