# Generated by Django 4.0.4 on 2022-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumb',
            field=models.ImageField(blank=True, default='image.jpg', null=True, upload_to=''),
        ),
    ]
