# Generated by Django 4.0.4 on 2022-08-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
