# Generated by Django 4.0.4 on 2022-08-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_user_profile_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='username',
        ),
    ]
