# Generated by Django 4.0.4 on 2022-08-02 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_rename_user_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
