# Generated by Django 4.0.4 on 2022-08-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='profile',
            new_name='author',
        ),
    ]
