# Generated by Django 4.0.4 on 2022-08-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
